### ISSUE TITLE
No way to get joke by ID (overalpping endpoints)

### ISSUE THREAD

**Issue by LucaBlackDragon** [eklavyadev/karljoke#5]
The endpoints ["Get number of random jokes by type"](https://github.com/eklavyadev/karljoke#get-number-of-random-jokes-by-type) and ["Get joke by type and id"](https://github.com/eklavyadev/karljoke/blob/main/README.md#get-joke-by-type-and-id) are overlapped and the latter one is not implemented in the code (while [the former one is](https://github.com/eklavyadev/karljoke/blob/8aefcc751421f756724472e97238d8fe786e3ee5/index.js#L44)), so I think it should be either implemented or removed from the README

**Comment by eklavyadev** [comment]
@LucaBlackDragon This was a silly mistake from my side, thanks for pointing out. Rather than changing everywhere else, I prefer keep this endpoint the other way
I changed the endpoint from `/jokes/{type}/{id}` to `/joke/{type}/{id}`. I hope this will help
Also will change documentation in frontend soon

**Comment by eklavyadev** [comment]
Thanks for pointing out
